site:
  name: TATAR Lab
  site: 'https://tatar-lab.github.io'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: TATAR Lab
    template: '%s | TATAR Lab'
  description: 'The TATAR Lab at the University at Albany, SUNY researches AI security and safety, cyber risk and insurance, and the protection of critical infrastructure.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: TATAR Lab
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
